name = "txt-sanitizer-v2"
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "txt_sanitizer_d1"
database_name = "txt-sanitizer-d1"
database_id = "10e1c684-acb9-483b-91d0-e4d658166693"